with-expecter: true
dir: test/mocks
outpkg: mocks
packages:
  github.com/evanrolfe/trayce_agent/internal/bpf_events:
    # place your package-specific config here
    config:
    interfaces:
      ContainersI:
      BPFModuleI:
