FROM ubuntu:22.04

WORKDIR /app
VOLUME [ "/app" ]

# Build dependencies:
RUN apt update -y
RUN apt install -y clang libelf1 libelf-dev zlib1g-dev make build-essential libz-dev libcap-dev llvm llvm-dev lld binutils-dev pkg-config linux-tools-generic wget gcc-multilib binutils git libssl-dev protobuf-compiler

# Debugging tools:
RUN apt install -y curl net-tools iproute2 dnsutils strace ltrace
# RUN apt install python3-pip ruby

# Install Go
RUN wget https://go.dev/dl/go1.20.4.linux-386.tar.gz
RUN tar -C /usr/local -xf go1.20.4.linux-386.tar.gz
ENV PATH "$PATH:/usr/local/go/bin:/root/go/bin"

# Go Build dependencies
RUN go install github.com/shuLhan/go-bindata/cmd/go-bindata@latest
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

CMD mount -t debugfs debugfs /sys/kernel/debug && bash
