version: 2.1

jobs:
  build-amd64:
    docker:
      - image: cimg/base:stable
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install docker buildx & login
          command: |
            docker buildx create --use --name mybuilder
            docker buildx inspect --bootstrap
      - restore_cache:
          keys:
            - v1-docker-build-cache-amd64-{{ checksum "Dockerfile" }}
            - v1-docker-build-cache-amd64
      - run:
          name: Build (multi-arch)
          command: |
            docker buildx build . \
              --platform linux/amd64,linux/arm64 \
              --tag traycer/trayce_agent:latest \
              --cache-from=type=local,src=/tmp/.buildx-cache \
              --cache-to=type=local,dest=/tmp/.buildx-cache-new
      - save_cache:
          key: v1-docker-build-cache-amd64-{{ checksum "Dockerfile" }}
          paths:
            - /tmp/.buildx-cache-new
  build-arm64:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install docker buildx & login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u $DOCKERHUB_USER --password-stdin
            docker buildx create --use --name mybuilder
            docker buildx inspect --bootstrap
      - restore_cache:
          keys:
            - v1-docker-build-cache-arm64-{{ checksum "Dockerfile" }}
            - v1-docker-build-cache-arm64
      - run:
          name: Build (multi-arch)
          command: |
            docker buildx build . \
              --platform linux/arm64 \
              --tag traycer/trayce_agent:latest \
              --cache-from=type=local,src=/tmp/.buildx-cache \
              --cache-to=type=local,dest=/tmp/.buildx-cache-new
      - save_cache:
          key: v1-docker-build-cache-arm64-{{ checksum "Dockerfile" }}
          paths:
            - /tmp/.buildx-cache-new
workflows:
  main:
    jobs:
      - build-arm64
      # - build-amd64
