version: 2.1

commands:
  build-and-test:
    description: Build and test
    steps:
      - run:
          name: Setup
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u $DOCKERHUB_USER --password-stdin
            wget -q https://go.dev/dl/go${GO_VERSION}.linux-${ARCH}.tar.gz -O /tmp/go.tar.gz
            tar -C /home/circleci/ -xf /tmp/go.tar.gz
            echo 'export PATH="$PATH:/home/circleci/go/bin/"' >> $BASH_ENV
      - run:
          name: Start Megaserver
          command: |
            GOARCH=${ARCH} go build -o test/scripts/go_request -buildvcs=false -gcflags "all=-N -l" ./cmd/request/
            GOARCH=${ARCH} go build -o test/mega_server/go -buildvcs=false -gcflags "all=-N -l" ./cmd/mock_server/
            docker build test/mega_server -t mega_server:${ARCH}
      - run:
          name: Build
          command: |
            docker build . -t traycer/trayce_agent:${ARCH}
      - run:
          name: Run
          command: |
            export HOST_IP=$(ifconfig eth1 | grep 'inet ' | awk '{print $2}')
            docker run -d --pid=host --privileged -v /var/run/docker.sock:/var/run/docker.sock -t traycer/trayce_agent:${ARCH} -s ${HOST_IP}:50051
      - run:
          name: Test
          command: make test
  push:
    description: Push the image to docker hub
    steps:
      - run:
          name: Push
          command: |
            docker push traycer/trayce_agent:${ARCH}

jobs:
  build-test-amd64:
    docker:
      - image: cimg/base:stable
    resource_class: large
    environment:
      GO_VERSION: 1.21.12
      ARCH: amd64
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: edge
      - build-and-test

  build-test-arm64:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.large
    environment:
      GO_VERSION: 1.21.12
      ARCH: arm64
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: edge
      - build-and-test

  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install docker buildx & login
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Create and Push Multi-Arch Manifest
          command: |
            docker manifest create traycer/trayce_agent:test \
              traycer/trayce_agent:amd64 \
              traycer/trayce_agent:arm64
            docker manifest push traycer/trayce_agent:test

workflows:
  main:
    jobs:
      - build-test-amd64
      # - build-test-arm64
      # - hold:
      #     type: approval
      #     requires:
      #       - build-arm64
      #       # - build-amd64
      # - publish:
      #     requires:
      #       - hold
          # filters:
          #   branches:
          #     only:
          #       - master

