#!/usr/bin/env node

const http = require('http');

http.get('http://www.pntest.io/', res => {
  let data = [];
  console.log('Status Code:', res.statusCode);

  res.on('data', chunk => {
    data.push(chunk);
  });

  res.on('end', () => {
    console.log('Response ended: ');
  });
}).on('error', err => {
  console.log('Error: ', err.message);
});
