#!/usr/bin/env ruby

require 'uri'
require 'net/http'

url = ARGV[0]
puts "Requesting URL: #{url}"
uri = URI(url)

http_session = Net::HTTP.new(uri.host, uri.port)
http_session.use_ssl = true
http_session.verify_mode = OpenSSL::SSL::VERIFY_NONE
res = http_session.start do |http|
  # do some requests here
  res = http.get(uri.path)
  puts res
end

