#!/usr/bin/env ruby

require 'uri'
require 'net/http'

url = ARGV[0]
puts "Requesting URL: #{url}"
uri = URI(url)

http_session = Net::HTTP.new(uri.host, uri.port)
res = http_session.start do |http|
  # do some requests here
  res = http.get(uri.path)
  puts res
end

puts "Process ID: #{Process.pid}"
