#!/usr/bin/env ruby

require 'socket'
server = TCPServer.new 4122
puts "Server running on port 4122"

while session = server.accept
  request = session.gets
  puts request

  session.print "HTTP/1.1 200\r\n"
  session.print "Content-Type: text/html\r\n"
  session.print "\r\n"
  session.print "Hello world (ruby)\n"

  session.close
end
