#!/usr/bin/env ruby

require "webrick"

=begin
    WEBrick is a Ruby library that makes it easy to build an HTTP server with Ruby.
    It comes with most installations of Ruby by default (it’s part of the standard library),
    so you can usually create a basic web/HTTP server with only several lines of code.

    The following code creates a generic WEBrick server on the local machine on port 1234,
    shuts the server down if the process is interrupted (often done with Ctrl+C).
    This example lets you call the URL's: "add" and "subtract" and pass through arguments to them
    Example usage:
        http://localhost:1234/ (this will show the specified error message)
        http://localhost:1234/add?a=10&b=10
        http://localhost:1234/subtract?a=10&b=9
=end

class MyServlet < WEBrick::HTTPServlet::AbstractServlet
    def do_GET (request, response)
        # puts "GET: #{request}"
        response.status = 200
        response.body = "Hello world (from ruby)"
    end
end

server = WEBrick::HTTPServer.new(:Port => 4122)

server.mount "/", MyServlet

trap("INT") {
    server.shutdown
}

server.start
